server:
  port: 8083
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  swagger:
    title: 支付服务接口文档
    package: com.hmall.user.controller
  db:
    database: hm-user
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true